export const S = {
  container: {
    display: "flex",
    "flex-direction": "column" as const,
    width: "100%",
    height: "100%",
    overflow: "hidden",
    color: "var(--text-primary, #f8fafc)",
    "font-family": "system-ui, -apple-system, sans-serif",
  },
  topBar: {
    display: "flex",
    "flex-direction": "column" as const,
    background: "rgba(var(--panel-rgb, 15, 23, 42), var(--plugin-surface-opacity, 0.75))",
    "backdrop-filter": "blur(var(--surface-blur, 12px))",
    "-webkit-backdrop-filter": "blur(var(--surface-blur, 12px))",
    "border-bottom": "1px solid var(--border-color, rgba(255, 255, 255, 0.08))",
    padding: "6px 12px",
    gap: "6px",
    "user-select": "none" as const,
  },
  tabRow: {
    display: "flex",
    "align-items": "center",
    gap: "6px",
    "overflow-x": "auto" as const,
    "scrollbar-width": "none" as const,
  },
  tab: {
    display: "inline-flex",
    "align-items": "center",
    gap: "8px",
    padding: "6px 12px",
    "border-radius": "8px",
    "font-size": "12px",
    "font-family": "Space Mono, monospace",
    color: "var(--text-secondary, #cbd5e1)",
    background: "var(--card-bg, rgba(255, 255, 255, 0.04))",
    border: "1px solid var(--card-border, rgba(255, 255, 255, 0.08))",
    cursor: "pointer",
    transition: "all 0.2s cubic-bezier(0.22, 1, 0.36, 1)",
    "max-width": "220px",
    "min-width": "120px",
    "white-space": "nowrap" as const,
    overflow: "hidden",
    "text-overflow": "ellipsis",
  },
  tabActive: {
    background: "rgba(var(--accent-rgb, 56, 189, 248), 0.15)",
    color: "var(--accent-default, #38bdf8)",
    border: "1px solid rgba(var(--accent-rgb, 56, 189, 248), 0.35)",
    "font-weight": 600,
    "box-shadow": "0 2px 8px rgba(0, 0, 0, 0.25)",
  },
  tabTitle: {
    overflow: "hidden",
    "text-overflow": "ellipsis",
    flex: 1,
  },
  tabCloseBtn: {
    display: "inline-flex",
    "align-items": "center",
    "justify-content": "center",
    width: "22px",
    height: "22px",
    "min-width": "22px",
    "min-height": "22px",
    padding: "0",
    "box-sizing": "border-box" as const,
    "border-radius": "4px",
    border: "none",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    opacity: 0.7,
    transition: "opacity 0.15s, background 0.15s",
    "flex-shrink": 0,
  },
  iconBtn: {
    display: "inline-flex",
    "align-items": "center",
    "justify-content": "center",
    width: "34px",
    height: "34px",
    "min-width": "34px",
    "min-height": "34px",
    padding: "0",
    "box-sizing": "border-box" as const,
    "border-radius": "6px",
    border: "1px solid var(--border-color, rgba(255, 255, 255, 0.1))",
    background: "var(--card-bg, rgba(255, 255, 255, 0.05))",
    color: "var(--text-primary, #f8fafc)",
    cursor: "pointer",
    transition: "all 0.2s cubic-bezier(0.22, 1, 0.36, 1)",
    "flex-shrink": 0,
  },
  cardIconBtn: {
    display: "inline-flex",
    "align-items": "center",
    "justify-content": "center",
    width: "30px",
    height: "30px",
    "min-width": "30px",
    "min-height": "30px",
    padding: "0",
    "box-sizing": "border-box" as const,
    "border-radius": "6px",
    border: "1px solid var(--card-border, rgba(255, 255, 255, 0.12))",
    background: "var(--card-bg, rgba(255, 255, 255, 0.06))",
    color: "var(--text-primary, #f8fafc)",
    cursor: "pointer",
    transition: "all 0.2s cubic-bezier(0.22, 1, 0.36, 1)",
    "flex-shrink": 0,
  },
  navRow: {
    display: "flex",
    "align-items": "center",
    gap: "8px",
    width: "100%",
  },
  omniboxContainer: {
    display: "flex",
    "align-items": "center",
    flex: 1,
    background: "var(--input-bg, rgba(0, 0, 0, 0.25))",
    border: "1px solid var(--border-color, rgba(255, 255, 255, 0.12))",
    "border-radius": "8px",
    padding: "0 10px",
    gap: "8px",
    height: "36px",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  omniboxInput: {
    flex: 1,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary, #f8fafc)",
    "font-family": "Space Mono, monospace",
    "font-size": "12.5px",
    width: "100%",
  },
  badge: {
    display: "inline-flex",
    "align-items": "center",
    gap: "4px",
    padding: "2px 8px",
    "border-radius": "4px",
    "font-size": "11px",
    "font-family": "Space Mono, monospace",
    "font-weight": 600,
    background: "rgba(var(--accent-rgb, 56, 189, 248), 0.12)",
    border: "1px solid rgba(var(--accent-rgb, 56, 189, 248), 0.25)",
    color: "var(--accent-default, #38bdf8)",
  },
  viewport: {
    position: "relative" as const,
    flex: 1,
    width: "100%",
    height: "100%",
    background: "var(--panel-bg, #080d1a)",
    overflow: "hidden",
  },
  iframe: {
    width: "100%",
    height: "100%",
    border: "none",
    display: "block",
    background: "#ffffff",
  },
  blockedNotice: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    "flex-direction": "column" as const,
    "align-items": "center",
    "justify-content": "center",
    background: "var(--panel-bg, rgba(15, 23, 42, 0.96))",
    "backdrop-filter": "blur(var(--surface-blur, 16px))",
    padding: "32px",
    gap: "16px",
    "text-align": "center" as const,
  },
  actionBtn: {
    display: "inline-flex",
    "align-items": "center",
    gap: "8px",
    padding: "8px 16px",
    background: "var(--accent-default, #38bdf8)",
    color: "#0f172a",
    "font-family": "Space Mono, monospace",
    "font-weight": 600,
    "font-size": "13px",
    border: "none",
    "border-radius": "6px",
    cursor: "pointer",
    transition: "transform 0.15s, opacity 0.15s",
  },
  secondaryBtn: {
    display: "inline-flex",
    "align-items": "center",
    gap: "8px",
    padding: "8px 16px",
    background: "var(--card-bg, rgba(255, 255, 255, 0.08))",
    color: "var(--text-primary, #f8fafc)",
    "font-family": "Space Mono, monospace",
    "font-weight": 500,
    "font-size": "13px",
    border: "1px solid var(--border-color, rgba(255, 255, 255, 0.15))",
    "border-radius": "6px",
    cursor: "pointer",
    transition: "all 0.15s",
  },
};
